### PR TITLE
Try to build a package with a package hash in the name

### PR DESCRIPTION
**Pull request by hmaarrfk**
Follow up to:
https://github.com/conda-forge/opencv-feedstock/pull/259

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
i finally think will fix things. I did have an issue with conflicting builds with python versions, which is why i added the python version to the build number.

I should have simply added the pkg_hash at the time.

Thank you @carterbox for getting to the bottom of the issue.

**Comment by hmaarrfk** [comment]
cpython
```
BUILD START: ['libopencv-4.5.0-py36h1da8354_7.tar.bz2', 'py-opencv-4.5.0-py36he448a4c_7.tar.bz2', 'opencv-4.5.0-py36ha770c72_7.tar.bz2']
```

pypy
```
BUILD START: ['libopencv-4.5.0-py36hb9094e3_7.tar.bz2', 'py-opencv-4.5.0-py36he2ddec3_7.tar.bz2', 'opencv-4.5.0-py36ha770c72_7.tar.bz2']
```

We need to add something to the opencv build to give it a different hash between pypy and cpython.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
build 1
```
BUILD START: ['libopencv-4.5.0-py36h1da8354_7.tar.bz2', 'py-opencv-4.5.0-py36he448a4c_7.tar.bz2', 'opencv-4.5.0-py36ha770c72_7.tar.bz2']
```
```
BUILD START: ['libopencv-4.5.0-py36hb9094e3_7.tar.bz2', 'py-opencv-4.5.0-py36he2ddec3_7.tar.bz2', 'opencv-4.5.0-py36ha770c72_7.tar.bz2']
```

**Comment by carterbox** [comment]
I think the `opencv` package doesn't require a unique hash because it is metapackage that doesn't directly depend on python. As long as the `libopencv` and `py-opencv` packages both depend on a python_abi and have unique hashes so the pypi version doesn't overwrite the cpython version it should work.

**Comment by carterbox** [comment]
If the python module `cv.[so, dylib]` was distributed as part of `py-opencv` instead of with `libopencv`, then only `py-opencv` would need a unique hash because `libopencv` would be independent of the python_abi. I can open a PR to do this separation this weekend if there is interest. I'm not sure why the package is not already split in the way I just described.

**Comment by hmaarrfk** [comment]
```
BUILD START: ['libopencv-4.5.0-py36hb9094e3_7.tar.bz2', 'py-opencv-4.5.0-py36he2ddec3_7.tar.bz2', 'opencv-4.5.0-py36hd000896_7.tar.bz2']
BUILD START: ['libopencv-4.5.0-py36h1da8354_7.tar.bz2', 'py-opencv-4.5.0-py36he448a4c_7.tar.bz2', 'opencv-4.5.0-py36h5fab9bb_7.tar.bz2']
```

**Comment by hmaarrfk** [comment]
Finally worked.

Unfortunately , I think the 

```
      run:
        - {{ pin_subpackage('libopencv', exact=True) }}
        - {{ pin_subpackage('py-opencv', exact=True) }}
```

would mean that we would only upload a single `opencv` package that would then pin to a spcific pypy or python3.6 (depending on whichever build gets uploaded).

We can probably loosen the pin, but it is MUCH easier to debug split packages when they are pinned to the exact other package that gets created at the same time.

**Comment by hmaarrfk** [comment]
@carterbox I'm not against a better recipe.

At the time, it mingwandroid was working on an other implementation
https://github.com/AnacondaRecipes/opencv-feedstock/tree/master/recipe

I felt it was too complicated without help from upstream to adapt their build system.

Happy to see what you can think of.


I think that this new build should help you though.

**Pull request merged**
