### PR TITLE
Blind sync with AD. Will update later.

### PR DESCRIPTION
**Pull request by hmaarrfk**
@mingwandroid here is effectively a blind sync. Lets see what happens.

Things to do:

- [ ] Do we need the openblas feature @jakirkham  @mingwandroid ???
- [x] ~~use ninja again to speedup windows a tiny bit~~ Ray uses jom to acheive the same thing.
- [x] update to 3.4.4

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@mingwandroid can you speak as to why you had to override channels?

**Comment by hmaarrfk** [comment]
what is happening here on linux:

```
+ [[ ! Linux =~ M* ]]
+ echo 'wtf 1 install-py-opencv.sh (top) PATH=/home/conda/feedstock_root/build_artifacts/opencv-suite_1548033187711/_build_env/bin:/home/conda/feedstock_root/build_artifacts/opencv-suite_1548033187711/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin'
wtf 1 install-py-opencv.sh (top) PATH=/home/conda/feedstock_root/build_artifacts/opencv-suite_1548033187711/_build_env/bin:/home/conda/feedstock_root/build_artifacts/opencv-suite_1548033187711/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin
+++ cygpath -u /opt/conda/bin/conda
/home/conda/feedstock_root/build_artifacts/opencv-suite_1548033187711/work/install-py-opencv.sh: line 17: cygpath: command not found
++ dirname
dirname: missing operand
Try `dirname --help' for more information.
++ cygpath -u /home/conda/feedstock_root/build_artifacts/opencv-suite_1548033187711/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
/home/conda/feedstock_root/build_artifacts/opencv-suite_1548033187711/work/install-py-opencv.sh: line 17: cygpath: command not found
```

**Comment by mingwandroid** [comment]
I override the channels just to be more explicit, shouldn't much matter though.

**Comment by hmaarrfk** [comment]
I think this build will pass now (hopefully) as I've used OpenCV's vendoered version of protobuf. I've also submitted PRs  to libprotobuf to make builds for the versions we need.

I've also noticed that in your version you refereed to version 3.5.1 in one location and 3.5.2 in an other.
Is that typo?

@mingwandroid I'll probably take you up on your offer to use jinja syntax to simplify the number of times build/host dependencies are listed.

I can probably hack at the other things on that todo list. Once this build passes.

FWIW, I think still think build process is too complicated.

My goal is mostly to get a respectable version of 3.4 out so we can create a 3.4 branch taht isn't too different from the 4.0 branch (or AD).

**Comment by hmaarrfk** [comment]
@mariusvniekerk Azure is failing with: no space left on device

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=6778

@mingwandroid it seems that the windows build just takes too long for our CIs....

**Comment by mingwandroid** [comment]
> FWIW, I think still think build process is too complicated.

I agree. We should look at making some precise changes to the CMake build scripts to allow passing an arbitrarily large number of Python executables to create bindings against. This would remove all of the complication from the build/install shell scripts and from meta.yaml. I've done a bit of research and think this is possible but I'm not at the stage where I've completely convinced myself yet.

**Comment by mingwandroid** [comment]
> @mingwandroid it seems that the windows build just takes too long for our CIs....

Yeah I agree it takes far too long. My arbitrary number of pythons proposal would fix that too.

**Comment by hmaarrfk** [comment]
got it. my only fear is that opencv changed things for 3.4.4.

I had done the work to get it to install in conda in this PR
https://github.com/conda-forge/opencv-feedstock/pull/132/files#diff-44a73bcc045c193c3bd45da87994b03b

I'll try to reincorporate it here. But I don't know how to work windows in with our CI limitations...

**Comment by mariusvniekerk** [comment]
@hmaarrfk we might want to try using the other drive for this, on windows there are two drives, we're technically using the smaller and slower one I think. I'll ask the Microsoft people

**Comment by hmaarrfk** [comment]
Well this builds, but lacks space on windows......

**Comment by hmaarrfk** [comment]
Appveyor gets to the point where tests fail on cmake:

https://ci.appveyor.com/project/conda-forge/opencv-feedstock/builds/21791267?fullLog=true#L17932

```
-- OpenCV STATIC: OFF
CMake Warning at C:/bld/opencv-suite_1548135824664/_test_env/Library/OpenCVConfig.cmake:156 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.
  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)
CMake Error at CMakeLists.txt:3 (find_package):
  Found package configuration file:
    C:/bld/opencv-suite_1548135824664/_test_env/Library/OpenCVConfig.cmake
  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.
```

**Comment by hmaarrfk** [comment]
@mariusvniekerk any idea why OSX passes on circle, but not azure?

**Comment by hmaarrfk** [comment]
My general thoughts on this is that it makes the recipe really complicated, for marginal gains for a user's perspective. 

The added complexity means that other maintainers will have a really hard time jumping in meaning added delays in releases and backports

**Pull request closed without merging**
