### PR TITLE
Fix Windows 64-bit builds

### PR DESCRIPTION
**Pull request by jakirkham**
Tries to switch to NMake to get 64-bit builds working again on the v2 branch.

### CODE REVIEW

**Comment by jakirkham** [comment]
Would like your feedback on this when you have a chance, @patricksnape.

**Comment by patricksnape** [comment]
Seems to be some kind of linking problem - will need to debug locally.

**Comment by jakirkham** [comment]
Ok. Please let me know if there is anything I can do to help.

**Comment by jakirkham** [comment]
This has already been resolved by PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/48 ). All Windows builds are passing. Closing...

**Pull request closed without merging**
