### PR TITLE
Add a pip check test

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
why?

**Comment by jan-janssen** [comment]
I have a pip package which depends on `opencv-python` and it fails when I execute `pip check`. So I expected this test to fail but it did not. https://github.com/conda-forge/imagedataextractor-feedstock

**Comment by hmaarrfk** [comment]
it might be because pip check isn't checking that `opencv-python` exists.

**Comment by hmaarrfk** [comment]
it is checking if the dependencies of opencv are met, but not opencv itself.

**Pull request closed without merging**
