### PR TITLE
add python 3.6 and numpy 1.12

### PR DESCRIPTION
**Pull request by peendebak**
Fixes https://github.com/conda-forge/opencv-feedstock/issues/53

### CODE REVIEW

**Comment by patricksnape** [comment]
This just needs rerendering - to remove Python 3.4 as well.

**Comment by eendebakpt** [comment]
@patricksnape So remove the python 3.4 build? And should I add the python 3.6, numpy 110 combination as well?

**Comment by patricksnape** [comment]
Rerendering with conda smithy will do that automatically

**Comment by peendebak** [comment]
@patricksnape Should I do something then? This conda smithy is new to me

**Comment by jakirkham** [comment]
ref: https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock

**Comment by peendebak** [comment]
@jakirkham @patricksnape The conda smithy package will not install:
```
(py35) C:\Users\eendebakpt>conda install -n root -c conda-forge conda-smithy
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - conda-smithy -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by jakirkham** [comment]
Might need to install on Python 3.5 for now.

**Comment by peendebak** [comment]
@jakirkham Making a python 3.5 env does not work for me either since conda-smithy needs to be installed in the root env. I will wait untill I can run this with python 3.6, or let someone else do the rerendering.

**Comment by jakirkham** [comment]
Right. So what I mean is you would need to change your `root` environment to Python 3.5 or 2.7 (e.g. `conda install -n root -c conda-forge python=35 conda-smithy`).

**Comment by peendebak** [comment]
@jakirkham I see what you mean, but I will not risk changing my root environment in this way.

**Comment by jakirkham** [comment]
Try with `conda-smithy` 2.1.0. There are Python 3.6 builds for that.

**Comment by peendebak** [comment]
@jakirkham Ok. Installing conda-smithy did a downgrade of conda, but it seems to have worked. I added a commit with the rerendering.

**Comment by jakirkham** [comment]
Seems GitHub doesn't recognize your email in the last commit. Adding that email to your GitHub account should fix it.

**Comment by jakirkham** [comment]
Looks like the Windows Python 2.7 32-bit builds are failing. That said, I think the issues are outside of the scope of this PR. So would be ok to merge as long as everything else passes. What do you think, @patricksnape?

**Comment by jakirkham** [comment]
Maybe we could squash the history @peendebak to make this a little cleaner.

**Comment by zym1010** [comment]
BTW, is there any plan for building numpy 1.12 enabled opencv 2.x? Many frameworks I need to use still are using OpenCV 2. Any pointer on how to build both 2 and 3? thanks.

**Comment by jakirkham** [comment]
Feel free to submit a [re-rendering]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) PR to the `v2` branch.

**Comment by mariusvniekerk** [comment]
Any idea whats the problem with the windows builds?

**Comment by zym1010** [comment]
@mariusvniekerk  try eigen 3.2.x. This is what makes windows builds on opencv 2.x fail

**Comment by jakirkham** [comment]
Given you fixed the other Windows builds for v2 and you know what needs to be done, do you want to give this a try @zym1010?

**Comment by zym1010** [comment]
@jakirkham sure. But how can I modify on top of this PR?

**Comment by jakirkham** [comment]
Assuming you have this as the remote `conda-forge` locally. One would do the following.

```bash
$ git fetch conda-forge refs/pull/51/head && git checkout FETCH_HEAD
```

This would put your repo in `detached HEAD` state on the latest commit in this PR. So probably want to checkout a branch after that and then go from there.

**Comment by mariusvniekerk** [comment]
Or use `hub` githubs extensions to git

**Comment by zym1010** [comment]
@jakirkham @mariusvniekerk check #59

**Comment by jakirkham** [comment]
Merged in with PR ( https://github.com/conda-forge/opencv-feedstock/pull/59 ). Thanks @zym1010.

**Comment by jakirkham** [comment]
Also thanks @peendebak for getting the ball rolling.

**Pull request merged**
