### PR TITLE
3.4.7

### PR DESCRIPTION
**Pull request by hmaarrfk**
lets start here.

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
maybe this is due to the lack of the updates to the recipe from @mshabunin. Will have to keep working at this.

**Comment by hmaarrfk** [comment]
@conda-forge/opencv I'll leave this open for a few days, but seems ready all together.

**Comment by patricksnape** [comment]
This looks good to me

**Comment by hmaarrfk** [comment]
Thanks @patricksnape merging this now!

**Pull request merged**
