### PR TITLE
Satisfy both conda-forge and defaults channel requirements

### PR DESCRIPTION
**Pull request by 183amir**
This pull allows me to install `opencv` alongside `anaconda=4` while also allowing other versions for `conda-forge` channel consistency.

### CODE REVIEW

**Comment by jakirkham** [comment]
Let's hold on this for a bit. I'm trying to see if we can get a bit more inline with `defaults` by downgrading some of these packages. We already have some problems like `qt` dependency compatibility issues, which we somehow need to address.

**Comment by 183amir** [comment]
This is not going to break anything, it will just add more flexibility.

**Comment by 183amir** [comment]
The Linux build is broken because of loose dependency tracking of `jpeg` in `jasper`:
```
jasper 1.900.1 0 linux-64          : jpeg
jasper 1.900.1 1 linux-64          : jpeg
jasper 1.900.1 2 linux-64          : jpeg 9b
```

**Comment by jakirkham** [comment]
It will eat up a bunch of build time though. If you try to add this to OpenCV 3.x, it won't work as we are already near the limit with CircleCI. Again let's please hold on this and figure out what we can do with these image libraries so we are not so out of sync with `defaults`.

**Pull request closed without merging**
