### PR TITLE
Update v2 to 2.4.13.4

### PR DESCRIPTION
**Pull request by patricksnape**
Passes on my OSX laptop

### CODE REVIEW

**Comment by patricksnape** [comment]
As usual - Windows is a nightmare - tempted to skip it for now and then put up another MR where we work on Windows

**Comment by jakirkham** [comment]
SGTM. TBH I think we would be pretty justified in dropping Windows for 2.x as it is Python 2 only and upstream has stated they don’t want to support VS2008.

**Comment by patricksnape** [comment]
❤️ Yes let's drop Windows

**Comment by patricksnape** [comment]
Alright and we are good - FFMPEG now works which sorts out #88

**Comment by patricksnape** [comment]
@jakirkham Builds are failing on the v2 branch but not on the MR? https://travis-ci.org/conda-forge/opencv-feedstock/builds/310842840

**Comment by patricksnape** [comment]
```
4.00s$ upload_or_check_non_existence ./recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Processing opencv
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 126, in <module>
    main()
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 115, in main
    upload(cli, meta, owner, channel)
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 64, in upload
    env=os.environ)
  File "/Users/travis/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', 'binstar.token', 'upload', '/Users/travis/miniconda3/conda-bld/osx-64/opencv-2.4.13.4-py27_blas_openblas_200.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
```

**Comment by jakirkham** [comment]
Think the Anaconda token's were out-of-date for this branch. So pulled them over from `master`. Should fix it.

**Comment by jakirkham** [comment]
In case people start wondering why we dropped Windows for this version, xrefing issue ( https://github.com/conda-forge/opencv-feedstock/issues/71 ).

**Comment by jakirkham** [comment]
macOS build now uploaded as well. :)

**Comment by patricksnape** [comment]
Thanks!

**Pull request merged**
