### PR TITLE
Update to OpenCV 3.2

### PR DESCRIPTION
**Pull request by mshunshin**
Change Version number and sha256 digest.

### CODE REVIEW

**Comment by jakirkham** [comment]
Toggling to get CircleCI.

**Comment by jakirkham** [comment]
Hmm...strangely it doesn't seem to start CircleCI. Could you try revoking CircleCI and readding them?

**Comment by patricksnape** [comment]
Unfortunately it isn't that simple! I started working on a build but it's complicated (as OpenCV always is, I can't even imagine the Windows builds....)

**Comment by patricksnape** [comment]
I've got a branch [here](https://github.com/menpo/conda-opencv3/tree/v3.2) that makes a start on making it work (should build for OSX)

**Comment by jakirkham** [comment]
Also you may actually just want to work on a branch on your fork for a bit with your own CIs enabled. The build time for OpenCV is quite long. Combined with the time you may spend waiting in the queue at conda-forge, you may be happier working on your fork. We would still be happy to help. Maybe you could start by creating a new branch and PRing it against your fork. That way we can discuss with you in that PR about how to get it built and make recommendations. Once you have a viable candidate, we can try again here. Does that sound reasonable?

**Comment by jakirkham** [comment]
Closing to consolidate the effort in PR ( https://github.com/conda-forge/opencv-feedstock/pull/50 ). Please feel free to participate in the discussion there.

**Pull request closed without merging**
