### PR TITLE
Explicitly enable dependency on protobuf to avoid runtime errors due to vendored protobuf

### PR DESCRIPTION
**Pull request by traversaro**
By default, OpenCV compiles and links a vendored old version of protobuf, that can create runtime problems when loaded in the same process where a library that links conda-forge's protobuf is loaded, such as the one reported in https://github.com/robotology/gym-ignition/pull/316 : 
~~~
[libprotobuf FATAL google/protobuf/stubs/common.cc:87] This program was compiled against version 3.5.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.15.6). Contact the program author for an update. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "../modules/dnn/misc/caffe/opencv-caffe.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
what(): This program was compiled against version 3.5.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.15.6). Contact the program author for an update. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "../modules/dnn/misc/caffe/opencv-caffe.pb.cc".)
~~~
This PR solve this problems by enabling explicitly the use of an external Protobuf.

See https://github.com/opencv/opencv/blob/4.5.1/cmake/OpenCVFindProtobuf.cmake#L9 for the OpenCV options used.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
There is a problem in `osx-arm64` builds as those are cross-compilation builds, so the protoc for the `build` platform should be used, not the one of the host. In theory it should be sufficient to install libprotobuf for the host, and specify that the build protoc should be used by setting the `Protobuf_PROTOC_EXECUTABLE` CMake variable.

**Comment by traversaro** [comment]
> 
> 
> There is a problem in `osx-arm64` builds as those are cross-compilation builds, so the protoc for the `build` platform should be used, not the one of the host. In theory it should be sufficient to install libprotobuf for the host, and specify that the build protoc should be used by setting the `Protobuf_PROTOC_EXECUTABLE` CMake variable.

See for example:
* https://github.com/conda-forge/grpc-cpp-feedstock/blob/d756d01bb13ae288d144907b340033f9e0684e3c/recipe/build.sh#L45
* https://github.com/conda-forge/grpc-cpp-feedstock/blob/d756d01bb13ae288d144907b340033f9e0684e3c/recipe/meta.yaml#L25

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge/opencv the recipe is ready for review, not sure about the Travis failure as it seems that it was failing for most recent PRs.

**Comment by hmaarrfk** [comment]
:/ i'm inclined to merge.

**Comment by hmaarrfk** [comment]
@conda-forge/arm-arch does anybody know why the power PC builds on travis might be failing recently?

**Comment by hmaarrfk** [comment]
one of the travis builds eventually passed. 

we can restart the travis builds as needed.

**Pull request merged**
