### PR TITLE
Don't build png, jpeg, tiff or zlib

### PR DESCRIPTION
**Pull request by patricksnape**
Seems to work in my VM for Py27 and Py34 - Py35 not tested.

### CODE REVIEW

**Comment by jakirkham** [comment]
I know AppVeyor is kind of backlogged. We are considering various options for improvement. In the meantime, could you set up an AppVeyor project for this repo and have it build that commit? Once it is done please link the logs so that we have them for posterity.

**Comment by patricksnape** [comment]
OK, Should be build [here](https://ci.appveyor.com/project/patricksnape/opencv-feedstock/build/1.0.2)

**Comment by patricksnape** [comment]
Waiting on Eigen...

**Comment by jakirkham** [comment]
Oh, sorry, I forgot that we were still waiting for that. This is fine.

**Comment by jakirkham** [comment]
Thanks @patricksnape. Sorry to hold this up.

**Pull request merged**
