### PR TITLE
v3.2.0

### PR DESCRIPTION
**Pull request by patricksnape**
Had to move Python detection on Unix back into the first CMake
call because the cache no longer seems to update.

### CODE REVIEW

**Comment by jakirkham** [comment]
If you want to incorporate PR ( https://github.com/conda-forge/opencv-feedstock/pull/48 ), I can close that out.

**Comment by patricksnape** [comment]
The single command for the Python options seems to stay concatenated together? This doesn't happen for me on either my Linux box or my Macbook. What's the best way to add all those options as a single bash variable?

**Comment by jakirkham** [comment]
Don't have time to debug this now, but could you please share a snippet from the log that is leaving you with this impression?

**Comment by patricksnape** [comment]
CircleCI
```
Could NOT find PythonInterp: Found unsuitable version "1.4", but required is at least "2.7" (found /feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python -DPYTHON_INCLUDE_DIR=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python2.7 -DPYTHON_LIBRARY=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libpython2.7.so -DPYTHON_PACKAGES_PATH=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages -DBUILD_opencv_python2=1 -DPYTHON2_EXECUTABLE=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python -DPYTHON2_INCLUDE_DIR=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python2.7 -DPYTHON2_NUMPY_INCLUDE_DIRS=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/numpy/core/include -DPYTHON2_LIBRARY=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libpython2.7.so -DPYTHON2_PACKAGES_PATH=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages)
-- Could NOT find PythonInterp: Found unsuitable version "1.4", but required is at least "2.6" (found /feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python -DPYTHON_INCLUDE_DIR=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python2.7 -DPYTHON_LIBRARY=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libpython2.7.so -DPYTHON_PACKAGES_PATH=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages -DBUILD_opencv_python2=1 -DPYTHON2_EXECUTABLE=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python -DPYTHON2_INCLUDE_DIR=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python2.7 -DPYTHON2_NUMPY_INCLUDE_DIRS=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/numpy/core/include -DPYTHON2_LIBRARY=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libpython2.7.so -DPYTHON2_PACKAGES_PATH=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages)
-- Could NOT find PythonInterp: Found unsuitable version "1.4", but required is at least "3.4" (found /feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python -DPYTHON_INCLUDE_DIR=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python2.7 -DPYTHON_LIBRARY=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libpython2.7.so -DPYTHON_PACKAGES_PATH=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages -DBUILD_opencv_python2=1 -DPYTHON2_EXECUTABLE=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python -DPYTHON2_INCLUDE_DIR=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python2.7 -DPYTHON2_NUMPY_INCLUDE_DIRS=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/numpy/core/include -DPYTHON2_LIBRARY=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libpython2.7.so -DPYTHON2_PACKAGES_PATH=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages)
-- Could NOT find PythonInterp: Found unsuitable version "1.4", but required is at least "3.2" (found /feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python -DPYTHON_INCLUDE_DIR=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python2.7 -DPYTHON_LIBRARY=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libpython2.7.so -DPYTHON_PACKAGES_PATH=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages -DBUILD_opencv_python2=1 -DPYTHON2_EXECUTABLE=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python -DPYTHON2_INCLUDE_DIR=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python2.7 -DPYTHON2_NUMPY_INCLUDE_DIRS=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/numpy/core/include -DPYTHON2_LIBRARY=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libpython2.7.so -DPYTHON2_PACKAGES_PATH=/feedstock_root/build_artefacts/recipe_root_1485294072974/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages)
```

Note the concatenated arguments

**Comment by patricksnape** [comment]
OK so windows is nearly building (except for VS2008 - classic) it just seems to be missing some of the contrib modules or they are named differently in Windows - need to get access to the list of files in `Library`.

OSX and Linux are killing me with their different behaviour from my local machine.

**Comment by patricksnape** [comment]
Linux works, Windows works barring my friend VS2008 and amazingly it's OSX that I've failed to get building. Although it seems there's just a missing lib or something

**Comment by patricksnape** [comment]
Current failures are strings not having the `.font()` member - so my `sed` replace failed me.

**Comment by sdvillal** [comment]
@patricksnape I think you will need to update harfbuzz to 1.4.

Also, could it be possible to directly use *patch* instead of *git patch* when applying the patch to contrib? Apparently git patch is brittle when the repo is cloned as a submodule. [Here is the little change that made it work for me](https://github.com/loopbio/opencv-feedstock/blob/b3872e2122d90ae0b13c0a10390107a03dddb05d/recipe/build.sh#L19-L24).

**Comment by patricksnape** [comment]
@sdvillal The current pinning for harfbuzz is [1.3](https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py#L40)

**Comment by patricksnape** [comment]
Cancelling Travis to reduce load - built locally on my Mac (will restart if Windows finally passes).

**Comment by jakirkham** [comment]
FWIW it looked like there were more issues with `data` being used with `std::vector` in `drawing.cpp` as well. TBH I'm a little surprised to see this many issues of this exact same form throughout the code base.

**Comment by patricksnape** [comment]
@jakirkham Made some progress but still stuck. Now failing in the dnn contrib module - tried to use patch on Windows but can't workout how to get it to work. Might need to use `git apply` instead since it can ignore whitespace. Right now it's totally broken because it just hangs.

**Comment by jakirkham** [comment]
Thanks @patricksnape. Definitely appreciate the effort. Will try to give it another look.

If you are looking for an easy win, PR ( https://github.com/conda-forge/yasm-feedstock/pull/9 ) might be it. 😉

**Comment by patricksnape** [comment]
[That was very time consuming](https://ci.appveyor.com/project/patricksnape/opencv-feedstock/build/1.0.72/job/7l5ko0ppsh8i49jh#L5548) 😪

**Comment by jakirkham** [comment]
What a mess! Can we get them to start testing with VS2008 in their CI? Maybe add AppVeyor or something? It's got to take less time to get that setup than mess with patching OpenCV every few months so it builds.

**Comment by jakirkham** [comment]
Could you restart CircleCI on your fork when you get a chance? Sadly CircleCI is not very smart about distinguishing builds on one's fork from a build in a PR let alone allowing both to occur.

**Comment by sdvillal** [comment]
Hats off to you @patricksnape

**Comment by patricksnape** [comment]
I will rebase all these commits and force push which should kick off new builds. Tonight I will open upstream PRs where necessary and also open an issue for OpenCV RE VS2008 builds.

**Comment by patricksnape** [comment]
Let's see if this builds through before I add the patches

**Comment by jakirkham** [comment]
> ...open an issue for OpenCV RE VS2008 builds.

Feel free to cc me on this.

**Comment by patricksnape** [comment]
I'm confused about CircleCI - this PR is only building my fork - is that OK?

**Comment by jakirkham** [comment]
I wouldn't worry about it.

Basically CircleCI will only build on your fork if you have enabled CircleCI to build on your fork. The result is it doesn't test the merge commit of the PR unlike other CIs, which can result in subtle problems sometimes. If you disabled CircleCI on your fork and repushed, it should build on the org instead.

**Comment by patricksnape** [comment]
But it will merge the new master push once this PR is merged?

**Comment by jakirkham** [comment]
Yeah once it is merged it will run on the org's CircleCI. So it shouldn't be an issue there.

**Comment by patricksnape** [comment]
Alright - well - OpenCV are being a bit slow - can we merge this and then I will reissue an MR when they decide if they support Python 2.7 - if they do then I will push the patches upstream and leave comments in the recipe here.

**Comment by jakirkham** [comment]
Absolutely. NP. Thanks very much for your hard work on this @patricksnape.

**Pull request merged**
