### PR TITLE
FFMPEG Attempt 2

### PR DESCRIPTION
**Pull request by patricksnape**
Rebuild now that FFMPEG contains `libavresample` ([here](https://github.com/conda-forge/ffmpeg-feedstock/pull/31)) - also make sure FFMPEG test should run (move to `run_test.py`)

### CODE REVIEW

**Comment by sdvillal** [comment]
Hi Patrick,

I'm happy to see that this is being taken care of. I think I have a solution for your failing test in linux. Try adding this to *build.sh*:

```sh
# See 
#   https://github.com/opencv/opencv/issues/8097
#   https://github.com/opencv/opencv/pull/8561
export CXXFLAGS="-D__STDC_CONSTANT_MACROS"
```
Doing so (on top of your pull request) works for me.

**Comment by patricksnape** [comment]
@sdvillal Thanks for the heads up - I had already found that issue so lets see if we build through now!

**Comment by sdvillal** [comment]
These circleci logs are looking pretty promising. If you need some review, I already can say LGTM.

In my limited experience, when dealing with videos, opencv tends to read or write garbage silently. After you merge these changes, what do you think about making the tests for video support a bit more complete and strict?  I can help and I would go this way: 

 - Check reading with all of the opencv test videos we know are supported: decode some frames and compare with a ground truth hash.
 - Run some roundtrip tests: generate a video, compress, decompress, check.

Just as a curiosity, this problem does not happen when using newer GCC versions - I build opencv 3.2 in my linux box without any trouble.

**Comment by patricksnape** [comment]
I would welcome a PR that implemented that!

**Pull request merged**
