### PR TITLE
4.2.0: jpeg image reading fix

### PR DESCRIPTION
**Pull request by hajapy**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@hmaarrfk I think jpg is also broken :( Adding a test case to demonstrate.

### CODE REVIEW

**Comment by hajapy** [comment]
on linux we get: JPEG_INCLUDE_DIR:PATH=$PREFIX/include
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=113546&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=ecca2736-6363-55be-133f-faae951bb9b5&l=2812

on osx we get: JPEG_INCLUDE_DIR:PATH=/Library/Frameworks/Mono.framework/Headers
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=113546&view=logs&j=15f8dc28-9f6f-5e3a-5b3c-2b169071e5be&t=0163009c-ae2d-56ec-96d8-026be7c15275&l=2465

**Comment by hmaarrfk** [comment]
Maybe let's define the variable in cmake?

**Comment by hajapy** [comment]
@hmaarrfk It looks like this is going to work. Do you think I should make more test cases before we redo the backports? Anything else to do on this also before a merge?

**Comment by hajapy** [comment]
@conda-forge-admin please rerender

**Pull request merged**
