### PR TITLE
Bump build number for #147

### PR DESCRIPTION
**Pull request by hmaarrfk**
See Issue #147

cc @pgunn

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
@conda-forge/opencv  @mariusvniekerk if you had time to quickly review this, this seems like it would help the OSX guys. Changes were kept to a minimum.

**Comment by hmaarrfk** [comment]
do we really care about the azure builds for OSX?

**Comment by mariusvniekerk** [comment]
Given that they pass now, why not.

**Comment by hmaarrfk** [comment]
maybe we should just add a comment in there saying that those are only for azure-OSX and that we can remove them once those scripts are addressed in smithy?

**Comment by jakirkham** [comment]
Thanks @hmaarrfk :)

**Pull request merged**
