### PR TITLE
Generate pkg-config info on Windows

### PR DESCRIPTION
**Pull request by auscompgeek**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

I am attempting to build a Python package ([robotpy-cscore](https://github.com/robotpy/robotpy-cscore)) that uses OpenCV as a library on Windows. We use pkgconfig to find OpenCV, for OpenCV 4 compatibility.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Thanks. Do you want to add a test to ensure that it is installed in the right location?

**Comment by auscompgeek** [comment]
Sounds like a good idea. I've added a test command in what is hopefully a reasonable spot.

**Comment by auscompgeek** [comment]
Well, it's a good thing I added that test. Hmm.

Upon closer inspection, it looks like OpenCV don't generate pkg-config info when building with MSVC:

https://github.com/opencv/opencv/blob/005508a07b42170e6a8d5f2ffba9aa5a1695054d/cmake/OpenCVGenPkgconfig.cmake#L1-L2

I wonder how one is supposed to discover include dirs on Windows then.

**Comment by auscompgeek** [comment]
I guess I'll close this for now, since this doesn't actually do anything useful.

**Pull request closed without merging**
