### PR TITLE
Opencv3 numpy112 py36

### PR DESCRIPTION
**Pull request by zym1010**
as a fix to #51

### CODE REVIEW

**Comment by jakirkham** [comment]
Awesome! Thanks @zym1010! 🎉

**Comment by jakirkham** [comment]
Would you be interested in being a maintainer of the `opencv` feedstock, @zym1010?

**Comment by zym1010** [comment]
@jakirkham  yeah sure!

**Comment by jakirkham** [comment]
Alright, could you please submit a PR adding yourself to the maintainer's list? Make sure to include `[ci skip]` in the commit message.

**Comment by zym1010** [comment]
@jakirkham  see #60

**Pull request merged**
