### PR TITLE
Remove VS workarounds

### PR DESCRIPTION
**Pull request by jakirkham**
Reverts: https://github.com/conda-forge/opencv-feedstock/pull/4
Fixes https://github.com/conda-forge/opencv-feedstock/issues/6

Removes the VS 2008 64-bit workaround that was added as this logic is now incorporated in `conda-build`. Also, re-renders the feedstock with `conda-smithy` 0.9.2. This includes any needed workarounds for any unresolved issues in `conda-build`.

Adds @msarahan as a maintainer based on this [comment]( https://github.com/conda-forge/opencv-feedstock/issues/5#issuecomment-212403459 ).

Finally, bumps the build number so we can get a clean build with this new setup.

### CODE REVIEW

**Comment by jakirkham** [comment]
@patricksnape @msarahan, looks like the `conda-build` fixes don't work in the case of OpenCV. Might want to take a look.

**Comment by jakirkham** [comment]
Closing as this is clearly broken.

**Comment by patricksnape** [comment]
The errors are because using the Python tools rules put the compiler specific generators - we should be using nmake for this to work now.

**Comment by jakirkham** [comment]
Sounds reasonable. Do you want to put together a PR?

**Pull request closed without merging**
