### PR TITLE
OpenCV 2.4.13 for numpy 1.11 and 1.12

### PR DESCRIPTION
**Pull request by zym1010**

### CODE REVIEW

**Comment by zym1010** [comment]
@jakirkham wonder why Windows and Mac builds are stuck...

**Comment by jakirkham** [comment]
They are queued behind other builds.

**Comment by zym1010** [comment]
@jakirkham thanks. BTW, looks that for OpenCV 2, I can't compile it with Eigen 3.x on Windows. Any idea about this? I think it doesn't really matter, as Eigen is bundled with opencv after compilation, and using an older one shouldn't matter.

**Comment by zym1010** [comment]
@jakirkham Mac builds really take forever... have you encountered it before?

**Comment by jakirkham** [comment]
Travis CI is getting pretty backlogged during the week. There are regularly ~100s to ~1000s of jobs backlogged throughout the week on Travis CI's Mac architecture.

**Comment by zym1010** [comment]
@jakirkham thank goodness it's done. How about merging it?

**Comment by zym1010** [comment]
@jakirkham  BTW, how do I somehow fork this recipe and upload it to my own anaconda cloud? As probably I want to modify it a little bit.

**Comment by zym1010** [comment]
@jakirkham  any update on merging it?

**Comment by jakirkham** [comment]
Thanks @zym1010. Sorry this got buried in the long stream of stuff that happens here all the time.

**Pull request merged**
