### PR TITLE
master: Add NumPy 1.13

### PR DESCRIPTION
**Pull request by jakirkham**
Re-render with `conda-smithy` 2.3.1 to add NumPy 1.13 to CI matrices.

### CODE REVIEW

**Comment by jakirkham** [comment]
This may push us right up to the time limit on CircleCI. If so, I'd suggest we explicitly drop NumPy 1.11. In the end, this will be something we do throughout conda-forge anyways.

**Comment by patricksnape** [comment]
This now takes too long - can we drop 1.11?

**Comment by patricksnape** [comment]
Ping @jakirkham do you think it's OK to drop 1.11?

**Comment by jakirkham** [comment]
That seems reasonable. My hands are just kind of full ATM as `conda` got upgraded in `conda-forge` and there are lots of things that broke as a consequence and need to be fixed and potentially pinned for the short term. Plus other work stuff.

**Comment by patricksnape** [comment]
I pushed removing 1.11 😄

**Comment by patricksnape** [comment]
No idea what that CircleCI error is - something to do with linking protobuf?

**Comment by isuruf** [comment]
It seems I've broken toolchain package. I'll revert the changes.

**Comment by jakirkham** [comment]
No need. Have pulled the Linux version. The rest aren't released yet, but can pull them as well.

**Comment by jakirkham** [comment]
FYI have worked up a proposal for CircleCI matrix support for `conda-smithy` in PR ( https://github.com/conda-forge/conda-smithy/pull/532 ). Please take a look.

**Pull request merged**
