### PR TITLE
Release 4.5.2

### PR DESCRIPTION
**Pull request by mshabunin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Release 4.5.2

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Did they bump the minimum requirements on OSX?

**Comment by mshabunin** [comment]
> Did they bump the minimum requirements on OSX?

I think no, looks like the problem is in the wechat_qrcode module which does not link with iconv library or there is a conflict between system iconv and the one installed as a dependency (`libiconv:        1.16-h642e427_0               conda-forge`), perhaps the solution from PR https://github.com/opencv/opencv_contrib/pull/2931 should fix it. I'll try to backport it and see if it works.

**Comment by hmaarrfk** [comment]
Builds are kinda passing. We might have to restart alt-arch. we can also try moving them to QEMU on azure

**Comment by mshabunin** [comment]
@hmaarrfk , builds have finally passed, but using Azure for ppc64le builds seems to be too inefficient, I think it will be better to revert it to TravisCI.

**Comment by hmaarrfk** [comment]
Seems like it passed

**Comment by mshabunin** [comment]
@hmaarrfk , I've restored Travis CI ppc64le builds and recombined commits. Builds have mostly passed except several ppc64le configurations. I don't have permissions to restart them.

**Comment by hmaarrfk** [comment]
Thanks lets restart as needed on master

**Pull request merged**
