### PR TITLE
integrate hotfix for ffmpeg support detection from upstream (PR 8561)

### PR DESCRIPTION
**Pull request by nlgranger**
Issue upstream: https://github.com/opencv/opencv/issues/8097
PR upstream: https://github.com/opencv/opencv/pull/8561

### CODE REVIEW

**Comment by nlgranger** [comment]
Not sure why the build is failing, works locally.
I think recipe/run_test.py should have failed before this patch, but I cannot find where it is called.

**Comment by jakirkham** [comment]
I think CircleCI is having some [issues]( https://status.circleci.com/incidents/sjqp9mkv9m4g ) with Docker. Maybe this will pass once that issue is resolved. Would wait on this until that happens.

**Comment by jakirkham** [comment]
Looks like the CircleCI issues have passed. Restarted the CircleCI build.

One of the Travis CI builds failed, but appeared spurious. So have gone ahead and restarted it to see if the issue resolves itself.

**Comment by patricksnape** [comment]
run_test.py automatically gets run by conda-build and already passes. I'm on my phone so it's hard to link but check the build.sh script, this issue is already fixed.

**Pull request closed without merging**
