### PR TITLE
bump to 3.4.2

### PR DESCRIPTION
**Pull request by hajapy**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by hajapy** [comment]
@conda-forge-admin, please rerender

**Comment by hajapy** [comment]
@conda-forge/core can you help debug this travis build failure? Could it be related to this change in conda-build 3.12.0? https://github.com/conda/conda-build/issues/3057

**Comment by isuruf** [comment]
You have to change the checksum at https://github.com/conda-forge/opencv-feedstock/blob/master/recipe/build.sh#L19

Instead of downloading in build.sh, I suggest using mutiple sources feature like https://github.com/AnacondaRecipes/opencv-feedstock/blob/master/recipe/meta.yaml#L15-L18

**Comment by hajapy** [comment]
Oh shoot, thx @isuruf. Will fix.

**Comment by hajapy** [comment]
It seems the windows builds are not finding the python libraries correctly (in both cases python3 appears in the `Unavailable:` line). Finding the right way to make the build happy on windows will probably be finicky and time consuming, so unless someone has a good hint to provide this may take a while to fix.

py35 build
```
[00:08:17] --   OpenCV modules:
[00:08:17] --     To be built:                 aruco bgsegm calib3d ccalib core cvv datasets dnn dnn_objdetect dpm face features2d flann fuzzy hfs highgui img_hash imgcodecs imgproc java_bindings_generator line_descriptor ml objdetect optflow phase_unwrapping photo plot python_bindings_generator reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
[00:08:17] --     Disabled:                    bioinspired js world
[00:08:17] --     Disabled by dependency:      -
[00:08:17] --     Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev freetype hdf java matlab ovis python2 python3 sfm ts viz

[00:08:17] --   Python 3:
[00:08:17] --     Interpreter:                 C:/bld/opencv_1533399395755/_h_env/python (ver 3.4.4)
[00:08:17] --     Libraries:                   NO
[00:08:17] --     numpy:                       C:/bld/opencv_1533399395755/_h_env/Lib/site-packages/numpy/core/include (ver )
[00:08:17] --     packages path:               C:/bld/opencv_1533399395755/_h_env/Lib/site-packages
[00:08:17] -- 
[00:08:17] --   Python (for build):            C:/bld/opencv_1533399395755/_h_env/python
```

py36 build
```
...
[00:08:10] --   OpenCV modules:
[00:08:10] --     To be built:                 aruco bgsegm calib3d ccalib core cvv datasets dnn dnn_objdetect dpm face features2d flann fuzzy hfs highgui img_hash imgcodecs imgproc java_bindings_generator line_descriptor ml objdetect optflow phase_unwrapping photo plot python_bindings_generator reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
[00:08:10] --     Disabled:                    bioinspired js world
[00:08:10] --     Disabled by dependency:      -
[00:08:10] --     Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev freetype hdf java matlab ovis python2 python3 sfm ts viz

[00:08:10] --   Python 3:
[00:08:10] --     Interpreter:                 C:/bld/opencv_1533399559735/_h_env/python (ver 3.4.4)
[00:08:10] --     Libraries:                   NO
[00:08:10] --     numpy:                       C:/bld/opencv_1533399559735/_h_env/Lib/site-packages/numpy/core/include (ver )
[00:08:10] --     packages path:               C:/bld/opencv_1533399559735/_h_env/Lib/site-packages
[00:08:10] -- 
[00:08:10] --   Python (for build):            C:/bld/opencv_1533399559735/_h_env/python
```

**Comment by jakirkham** [comment]
Superceded by PR ( https://github.com/conda-forge/opencv-feedstock/pull/125 ).

**Pull request closed without merging**
