### PR TITLE
Add qt4 for linux build to make cv2.imshow() work

### PR DESCRIPTION
**Pull request by hajapy**
Should address https://github.com/conda-forge/opencv-feedstock/issues/79

### CODE REVIEW

**Comment by jakirkham** [comment]
Why we are pinning to Qt4? Also why is macOS not built with Qt?

**Comment by jakirkham** [comment]
Canceling AppVeyor for now as there is an issue with `conda` on that platform ATM, which will cause the build to hang and then fail.

**Comment by hajapy** [comment]
On our own build infrastructure we've managed to make a similar recipe work with qt4 but not 5. I am willing to try it with qt5 if that is important. 

Mac os build picks up Cocoa and works well with that.

**Comment by jakirkham** [comment]
Most of the conda-forge stack is using Qt5. Using Qt4 would make it hard to install OpenCV with other conda-forge package's using Qt.

I see. Still it might be nice to have some consistency between platforms. Using Qt across the board would give us that.

**Comment by hajapy** [comment]
It's important to note that although the builds have passed, I suspect the state of affairs is as follows. 

OS X: highgui (cv2.imshow) uses Cocoa bindings
Linux: highgui (cv2.imshow) uses QT 4 bindings
Windows: highgui likely not enabled. 

I will open a separate PR with all platforms attempting to bind to QT5. If we can verify that all works as expected there, we should prefer that solution to this one.

It will be important to somehow test these builds on each platform. However, I do not know how to automate a test that creates a window and ensures it existence.. nor how to get at the build packages (before merging and upload to anaconda.org) for offline testing.

**Comment by hajapy** [comment]
Closing in favor of https://github.com/conda-forge/opencv-feedstock/pull/81

**Pull request closed without merging**
