### PR TITLE
split packages for opencv

### PR DESCRIPTION
**Pull request by hmaarrfk**
Retrying #149

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge/opencv how do you feel about this one. It allows us to provide packages that are installable without python, and enables us to match the default naming convention. All without significantly increasing the complexity of this recipe

* https://anaconda.org/anaconda/libopencv
* https://anaconda.org/anaconda/py-opencv
* https://anaconda.org/anaconda/opencv

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by patricksnape** [comment]
Won't this be an issue for everyone who already has the opencv containing Python already? I like that it now matches defaults but I'm just concerned for downstream users who already have pipelines setup that rely on opencv with Python being called just "opencv" and then this update breaking that?

**Comment by hmaarrfk** [comment]
The opencv package as is still depends on python, it is just now a meta package that doesn't contain much

**Comment by patricksnape** [comment]
Ah sorry misunderstood 😄 then this seems really cool to me

**Comment by hmaarrfk** [comment]
Let's set a release date of Sept 1st for this? I want to give time for others at @conda-forge/opencv to vito such a big change to organization

**Comment by hmaarrfk** [comment]
September first is done! Letsmerge this!

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by patricksnape** [comment]
🎉

**Pull request merged**
