### PR TITLE
Disable OPENCV_SKIP_PYTHON_LOADER option to ensure that .pyi files are installed

### PR DESCRIPTION
**Pull request by traversaro**
Hopefully this will fix https://github.com/conda-forge/opencv-feedstock/issues/374 without creating additional problems.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
do you want to add a test?

**Comment by hmaarrfk** [comment]
I wonder if it is finally time to drop qt5 and ffmpeg6

**Comment by traversaro** [comment]
> do you want to add a test?

@Unturned3 @carschandler any idea for a reasonable test? I never used `.pyi` files, so I would just check the existence of the main `.pyi` in the root folder.

**Comment by traversaro** [comment]
> I wonder if it is finally time to drop qt5 and ffmpeg6

Yes, I wanted to first check if there was any regression of this hence the full build, if I start iterating on it I will disable the builds.

**Comment by carschandler** [comment]
I think the main goal is to have LSP recognize the types but I’m not sure a great way to test that programmatically, so I think just checking the existence of the pyi files is good enough!

Also, it seems like this is on the right track as this is the PR that was just merged in nixpkgs to fix the same issue.

https://github.com/NixOS/nixpkgs/pull/317546

**Comment by hmaarrfk** [comment]
Perhaps we can pull in the changes from https://github.com/conda-forge/opencv-feedstock/pull/436 (if that PR works) into here and just merge.

Then get some feedback from users.

**Comment by traversaro** [comment]
> Perhaps we can pull in the changes from https://github.com/conda-forge/opencv-feedstock/pull/436 (if that PR works) into here and just merge.
> 
> Then get some feedback from users.

I am away from office for work all week, I can try do it but if anyone wants to do it before me, feel free to do it!

**Comment by hmaarrfk** [comment]
hmm i guess i closed the FFMPEG 6/7 dual builds. only ffmpeg7 now! whohooo!

**Comment by traversaro** [comment]
Thanks!

**Pull request merged**
